version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - mysql_minha_rede
    volumes:
      - ".:/usr/src/app"
    stdin_open: true
    command: npm start -- --port 3000
    
networks:
  mysql_minha_rede:
    external: true
